version: '3'
services:
  manager:
    build:
      context: ../manager
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      #- AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIA2UC3AT3EFYHIYTLR
      - AWS_SECRET_ACCESS_KEY=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

      
    
