version: '3'
services:
  manager:
    build:
      context: ../manager
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      #- AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIA2UC3AT3EGG3R726A
      - AWS_SECRET_ACCESS_KEY=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

      
    
